structure:
  classifier: "ResNet152" # 分类器结构
  dataset: "ImageNet-Mini" # 数据集，可选 [MNIST, CIFAR10, ImageNet,ImageNet-5k,ImageNet-Mini]
  bsize: 2 # 批次大小，在 4090 上运行
  run_samples: 50000 # 运行的样本数量
  interpreter_names: ['GradientShap', 'IntegratedGradients'] # 解释方法名称
  mask_type: 'steps_interpretation' #掩码方法，可选 [rcam, interpretation, rcam_interpretation, steps_interpretation, steps_rcam_interpretation]
  start_epoch: 0 # 开始的 epoch
  end_epoch: 50000000000 # 结束的 epoch

net:
  attention_resolutions: 32,16,8
  batch_size: 30
  channel_mult: ''
  class_cond: false
  clip_denoised: true
  diffusion_steps: 1000
  dropout: 0.0
  image_size: 256
  learn_sigma: true
  noise_schedule: linear
  num_channels: 256
  num_head_channels: 64
  num_heads: 4
  num_heads_upsample: -1
  num_res_blocks: 2
  num_samples: 10000
  predict_xstart: false
  resblock_updown: true
  rescale_learned_sigmas: false
  rescale_timesteps: false
  timestep_respacing: '250'
  use_checkpoint: false
  use_ddim: false
  use_kl: false
  use_new_attention_order: false
  use_scale_shift_norm: true
  model_path: "models/256x256_diffusion_uncond.pt" # 扩散模型路径
  use_fp16: true # 是否使用半精度浮点数

attack:
  if_attack:  true # 是否获取对抗样本
  attack_method: "autoAttack" # 攻击方法，可选 [clf_pgd, bpda, spsa]
  ptb: 4. # 扰动幅度，像素尺度
  attack_lambda: 0.05 # 自适应攻击步长策略
  attack_steps: 40 # 攻击步骤数
  iter: 40 # 基于梯度的攻击迭代次数

purification:
  guide_mode: "L2_CONSTANT" # 引导模式，可选 [MSE, SSIM, L2, L2_CONSTANT]
  max_iter: 1 # 默认最大迭代次数
  purify_step: 45 # 净化步骤数
  st: 170 #步数阈值
  threshold_all: 0 #全局语义保留阈值
  threshold_false: 0.6 #主体区域语义保留阈值
  threshold_rcam: 0.6 #RCAM区域语义保留阈值
  guide_scale: 1 # 引导缩放因子 L2_CONSTANT设置为1 MSE SSIM设置为1000

device: "cuda" # 使用的设备
rank: 0 #0:干净样本无掩码；1:干净样本有掩码 2:对抗样本无掩码；3:对抗样本有掩码
