structure:
  classifier: "ResNet50" # 分类器结构
  dataset: "ImageNet-Mini" # 数据集，可选 [MNIST, CIFAR10, ImageNet,ImageNet-5k,ImageNet-Mini]
  bsize: 2 # 批次大小，在 4090 上运行
  run_samples: 50000 # 运行的样本数量
  interpreter_names: ['GradientShap'] # 解释方法名称
  mask_type: 'steps_interpretation' #掩码方法，可选 [rcam, steps_interpretation, steps_rcam_interpretation]
  start_epoch: 0 # 开始的 epoch
  end_epoch: 10 # 结束的 epoch

net:
  attention_resolutions: 32,16,8
#  batch_size: 30
  channel_mult: ''
  class_cond: false
  clip_denoised: true
  diffusion_steps: 1000
  dropout: 0.0
  image_size: 256
  learn_sigma: true
  noise_schedule: linear
  num_channels: 256
  num_head_channels: 64
  num_heads: 4
  num_heads_upsample: -1
  num_res_blocks: 2
  num_samples: 10000
  predict_xstart: false
  resblock_updown: true
  rescale_learned_sigmas: false
  rescale_timesteps: false
  timestep_respacing: '250' #去噪总步数                                                -----
  use_checkpoint: false
  use_ddim: false #                                                                   -----
  use_fp16: true
  use_kl: false
  use_new_attention_order: false
  use_scale_shift_norm: true
  path: "/home/fcc/codefile/HGDM/models/256x256_diffusion_uncond.pt" # 扩散模型路径

attack:
  if_attack:  true # 是否获取对抗样本
  if_targeted:  false #  是否为定向攻击
  attack_method: "clf_pgd" # 攻击方法，可选 [clf_pgd, bpda, spsa]
  ptb: 4. # 扰动幅度，像素尺度
  ball_dim: -1 # 范数类型，-1 或 1 或 2
  n_eot: 1 # EOT（期望变换）次数，1 表示不应用 EOT
  attack_lambda: 0.05 # 自适应攻击步长策略
  attack_steps: 100 # 攻击步骤数
  iter: 40 # 迭代次数
  paper: "GDMAP_ORG_steps_interpretation_gaussian_blur_5_1"


purification:
  max_iter: 1 # 最大迭代次数
  threshold_adv_min: 0 #全局语义保留阈值
  threshold_focus_min: 0.6 #主体区域语义保留阈值
  mask_step: 30 # 掩码步数                                                                  -----
  purify_step: 45 # 加噪步数                                                              -----
  cond: true # 是否使用条件去噪                                                              -----
  guide_mode: "SSIM" # 引导模式，可选 [MSE, SSIM, L2, L2_CONSTANT]
  guide_scale: 1000 # 引导缩放因子 L2_CONSTANT设置为2 MSE SSIM设置为1000
#  guide_scale_base: 'per=4'
  mask_root: "exponential" #  掩码路径 linear exponential beta_t
  exponential_k: 3.0
  path_number: 1 # 多结果集成路径数量
  classify_all_steps: false # 是否对所有步骤进行分类
  guide_image: "ordered_dithering" # 引导图像类型，可选 [gaussian_blur, wavelet_denoise, freq_filter, ordered_dithering]

device: "cuda" # 使用的设备
rank: 0 #0:干净样本无掩码；1:干净样本有掩码 2:对抗样本无掩码；3:对抗样本有掩码
grad_enabled: false # 是否启用梯度计算,pgd-eot时需要开启